[build]
builder = "nixpacks"

[deploy.services.frontend]
path = "client"
startCommand = "npm run build && npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.services.backend]
path = "server"
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100